# Add 'root' label to any root file changes
# Quotation marks are required for the leading asterisk
root:
- changed-files:
  - any-glob-to-any-file: '*'

# Add 'AnyChange' label to any changes within the entire repository
AnyChange:
- changed-files:
  - any-glob-to-any-file: '**'

# Add 'Documentation' label to any changes within 'docs' folder or any subfolders
Documentation:
- any:
  - changed-files:
    - any-glob-to-any-file: docs/**
    - any-glob-to-any-file: '**/*.md'

# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
 - head-branch: ['^feature', 'feature']

enhancement:
  - head-branch: ['^feature', 'feature']

# Add 'bug' label to any PR where the head branch name starts with 'bug' or has a 'bug' section in the name
bug:
    - head-branch: ['^bug', 'bug']

 # Add 'release' label to any PR that is opened against the `main` branch
release:
 - base-branch: 'main'